"use client";

import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function ForgotPasswordForm() {
  const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch("/api/auth/forgot-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Unable to send reset email."); else setSent(true); setBusy(false); }
  return <div className="mx-auto grid min-h-screen max-w-lg place-items-center px-5"><section className="w-full rounded-md border border-[#CFE0DB] bg-white p-6 shadow-xl sm:p-8"><Link href="/login" className="inline-flex items-center gap-2 text-sm font-bold text-[#087B69]"><ArrowLeft className="h-4 w-4" />Back to sign in</Link><h1 className="mt-7 text-3xl font-extrabold text-[#143A35]">Reset your password</h1><p className="mt-3 text-sm leading-6 text-[#60756F]">We will send a secure reset link to your registered email.</p>{sent ? <div className="mt-6 rounded-md border border-[#AFCFC7] bg-[#EAF8F4] p-4 text-sm font-semibold text-[#08705F]"><CheckCircle2 className="mb-2 h-5 w-5" />If that account exists, the reset email is on its way.</div> : <form onSubmit={submit} className="mt-6 grid gap-4"><label className="grid gap-1.5 text-xs font-bold text-[#38534D]">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12 rounded-md border border-[#CFE0DB] px-4 text-sm outline-none focus:border-[#08A98A]" /></label>{error ? <p role="alert" className="rounded-md border border-[#FFC1BA] bg-[#FFF0EE] px-3 py-2 text-sm font-semibold text-[#A93931]">{error}</p> : null}<button disabled={busy} className="inline-flex h-12 items-center justify-center gap-2 rounded-md bg-[#006E5B] text-sm font-bold text-white disabled:opacity-60">{busy ? "Sending..." : "Send reset link"}<ArrowRight className="h-4 w-4" /></button></form>}</section></div>;
}

export function UpdatePasswordForm() {
  const router = useRouter(); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const response = await fetch("/api/auth/update-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Unable to update password."); else router.push("/dashboard"); setBusy(false); }
  return <div className="mx-auto grid min-h-screen max-w-lg place-items-center px-5"><section className="w-full rounded-md border border-[#CFE0DB] bg-white p-6 shadow-xl sm:p-8"><h1 className="text-3xl font-extrabold text-[#143A35]">Choose a new password</h1><form onSubmit={submit} className="mt-6 grid gap-4"><label className="grid gap-1.5 text-xs font-bold text-[#38534D]">New password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-12 rounded-md border border-[#CFE0DB] px-4 text-sm outline-none focus:border-[#08A98A]" /></label>{error ? <p role="alert" className="rounded-md border border-[#FFC1BA] bg-[#FFF0EE] px-3 py-2 text-sm font-semibold text-[#A93931]">{error}</p> : null}<button disabled={busy} className="inline-flex h-12 items-center justify-center gap-2 rounded-md bg-[#006E5B] text-sm font-bold text-white disabled:opacity-60">{busy ? "Updating..." : "Update password"}<ArrowRight className="h-4 w-4" /></button></form></section></div>;
}
